[project]
name = "mlops-image-classification"
version = "0.1.0"
description = "MLOps project: Image Classification"
authors = [
    {name = "TM-Squared",email = "malaury.toussi@gmail.com"}
]
license = {text = "LICENCE"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
