name: Tests dans Docker

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create test environment file
      run: |
        cp .env.example .env
    
    - name: Run tests in Docker
      run: |
        chmod +x scripts/run_tests_docker.sh
        ./scripts/run_tests_docker.sh
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Docker Tests Results
        path: test-results/junit.xml
        reporter: java-junit
